name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:${{ github.sha }}
          ghcr.io/${{ github.repository }}:latest

    - name: Create .nojekyll file to bypass Jekyll processing
      run: echo > .nojekyll

    - name: Create index.html file
      run: |
        echo "<html>" > index.html
        echo "<body>" >> index.html
        echo "<h1>Docker Image Published!</h1>" >> index.html
        echo "<p>Docker Image: ghcr.io/${{ github.repository }}:latest</p>" >> index.html
        echo "</body>" >> index.html
        echo "</html>" >> index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
